version: '3'
services:
  backend:
    build: ./backend
    ports:
      - 5000:5000
    restart: always
  frontend:
    build: ./frontend
    ports:
      - 80:80
    restart: always
    depends_on:
      - backend
